### ISSUE TITLE
caffe version

### ISSUE THREAD

**Issue by kingvision** [camel007/caffe-moon#1]
HI:
   If i train the caffe-moon my model, i should use which caffe version is.
   I think the model input is multi-lables data, is right?
thanks

**Comment by camel007** [comment]
Thanks for your concern
Currently, I use the latest version of caffe.

**Comment by camel007** [comment]
Yes, the input is multi-labels data. I have updated the scripts for generate lmdb database. please check

**Comment by kingvision** [comment]
Thanks, I will check
