### ISSUE TITLE
Using convert_imageset_multi_label

### ISSUE THREAD

**Issue by aliosia** [camel007/caffe-moon#3]
Hi, 
How should I compile and use convert_imageset_multi_label.cpp?
Thanks

**Comment by camel007** [comment]
Put 'convert_imageset_multi_label.cpp' caffe_root/tools  and rebuild caffe


2017-01-24 15:08 GMT+08:00 Seyed Ali Ossia <notifications@github.com>:

**Comment by aliosia** [comment]
Thanks. I have another question:
What is the Normalize layer in your models? I can not find it in caffe layers documentation and also I get error on that.

**Comment by camel007** [comment]
Sorry, I forgot include this in repo, I will update my repo later. Thank
you!

2017-01-24 19:24 GMT+08:00 Seyed Ali Ossia <notifications@github.com>:

**Comment by AliShahin** [comment]
Hi,
When you put the normalize layer in your repo? It is not in official caffe.

Thanks,

**Comment by camel007** [comment]
#https://github.com/camel007/caffe-moon/issues/4

**Comment by AliShahin** [comment]
I've seen #4. But it is a caffe version for windows. I want to use it on Ubuntu.

**Comment by camel007** [comment]
Put the normalize layer in you caffe sorce code then compile.

**Comment by AliShahin** [comment]
Should I uninstall the current version and again make it or just rebuilt it?
