### ISSUE TITLE
Incompatible number of blobs for layer norm_conv8_max

### ISSUE THREAD

**Issue by ysc703** [camel007/caffe-moon#5]
Hi 
   When using the prototxt and caffemodel in the caffe-windows version, I got the error as follow:
   net.cpp:773] Check failed: target_blobs.size() == source_layer.blobs_size() (1 vs. 0) Incompatible number of blobs for layer norm_conv8_max

   I try to find the problem, but failed. Can you give me some suggestion?
   Thank you!

**Comment by 32l** [comment]
have you solved the problem? How?
